#pragma once
#include "Types.h"
#include "AudioEngine.h"
#include "Project.h"
struct AppState {
    Project project;
    Transport transport;
    AudioEngine* engine = nullptr;
    AudioSettings audioSettings;
    bool showPianoRoll = false;
    bool showPlaylist = true;
    bool showMixer = false;
    bool showBrowser = true;
    bool showChannelRack = true;
    bool showExportDialog = false;
    bool showAboutDialog = false;
    float pianoRollZoomX = 20.0f;
    float pianoRollZoomY = 1.5f;
    int pianoRollScrollX = 0;
    int pianoRollScrollY = 40;
    int pianoRollEditingNote = -1;
    int pianoRollDragNote = -1;
    bool pianoRollDragging = false;
    int pianoRollDragStartX = 0;
    int pianoRollDragStartY = 0;
    int pianoRollDragStartKey = 0;
    int pianoRollDragStartTick = 0;
    int pianoRollResizingNote = -1;
    bool pianoRollResizing = false;
    int pianoRollPreviewKey = -1;
    int playlistScrollX = 0;
    int playlistScrollY = 0;
    float playlistZoomX = 8.0f;
    int browserSelected = -1;
    std::string browserPath;
    std::vector<std::string> browserFiles;
    std::vector<bool> browserIsDir;
    int dragSourcePattern = -1;
    int dragSourceNote = -1;
    char statusMessage[256] = "";
    float statusTimer = 0.0f;
    bool actionOpen = false;
    bool actionSaveAs = false;
    bool actionImportMIDI = false;
    float masterVolume = 1.0f;
    int exportSampleRate = 44100;
    char exportPath[1024] = "";
    std::vector<Project> undoStack;
    std::vector<Project> redoStack;
    int pianoRollSnap = 4;
    bool pianoRollSnapEnabled = true;
    int renameChannelIndex = -1;
    int pendingAction = 0;
    bool pianoRollDragPushedUndo = false;
    bool playlistDragPushedUndo = false;
    int playlistDragStartMouseX = 0;
    int playlistDragStartMouseY = 0;
    int playlistDragOrigTick = 0;
    int playlistDragOrigTrack = 0;
    bool requestQuit = false;
    bool pianoRollScrolling = false;
    int pianoRollScrollStartX = 0;
    int pianoRollScrollStartY = 0;
    int pianoRollScrollOrigX = 0;
    int pianoRollScrollOrigY = 0;
};

bool appInit(AppState& state, AudioEngine* engine);
void appRender(AppState& state, float deltaTime);
void appShutdown(AppState& state);
bool appSaveProject(AppState& state, const char* path);
bool appLoadProject(AppState& state, const char* path);
bool appExportWAV(AppState& state, const char* path);
bool appImportMIDI(AppState& state, const char* path);
bool appExportMIDI(AppState& state, const char* path);
void renderTheme();
void renderMainMenu(AppState& state);
void renderTransportBar(AppState& state);
void renderChannelRack(AppState& state);
void renderPianoRoll(AppState& state);
void renderPlaylist(AppState& state);
void renderMixer(AppState& state);
void renderBrowser(AppState& state);
void renderExportDialog(AppState& state);
void renderAboutDialog(AppState& state);
void renderConfirmationDialog(AppState& state);
void refreshBrowser(AppState& state, const char* path);
void addChannel(AppState& state, bool isSampler);
void addSF2Channel(AppState& state);
void addPattern(AppState& state);
void setStatus(AppState& state, const char* fmt, ...);
void pushUndo(AppState& state);
void undo(AppState& state);
void redo(AppState& state);
